### ISSUE TITLE
404 on adaptive downloads

### ISSUE THREAD

**Issue by kpister** [pytube/pytube#717] opened 2020-08-12 14:35 UTC
I'm getting a 404 from youtube when I attempt to download adaptive streams. Progressive is fine, but those aren't the highest quality videos. Is there a work around for this one?

```
from pytube import YouTube
yt_video = YouTube("https://www.youtube.com/watch?v=xFSVoVOvaew")
yt_video.streams.filter(adaptive=True).order_by('resolution').first().download()
```

Returns
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kaiser/tmp/pytube/pytube/streams.py", line 245, in download
    bytes_remaining = self.filesize
  File "/Users/kaiser/tmp/pytube/pytube/streams.py", line 156, in filesize
    self._filesize = request.filesize(self.url)
  File "/Users/kaiser/tmp/pytube/pytube/request.py", line 86, in filesize
    return int(head(url)["content-length"])
  File "/Users/kaiser/tmp/pytube/pytube/request.py", line 98, in head
    response_headers = _execute_request(url, method="HEAD").info()
  File "/Users/kaiser/tmp/pytube/pytube/request.py", line 27, in _execute_request
    return urlopen(request)  # nosec
  File "/Users/kaiser/.pyenv/versions/3.8.2/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/kaiser/.pyenv/versions/3.8.2/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/kaiser/.pyenv/versions/3.8.2/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Users/kaiser/.pyenv/versions/3.8.2/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/kaiser/.pyenv/versions/3.8.2/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/kaiser/.pyenv/versions/3.8.2/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by kpister** [comment] 2020-10-12 01:34
This is still an issue, it should not be marked as stale.

**Comment by unremarkablegarden** [comment] 2020-10-29 11:46
+1

**Comment by RONNCC** [comment] 2020-10-31 10:10
@tfdahlin Could you assist with this when you get a minute?

**Comment by tfdahlin** [comment] 2020-10-31 17:34
I'll look into it

**Comment by xielongze** [comment] 2020-11-04 05:34
I'm running into the same issue. Do you have any idea what's going on?

**Comment by tfdahlin** [comment] 2020-11-04 23:35
@xielongze still trying to figure out what the issue is. I'm not as familiar with how the stream object code works, so it's taking me a little while to chew through it and figure out the problem

**Comment by tfdahlin** [comment] 2020-11-05 02:13
I've identified the problem, and I'm working on a fix.

It looks like YouTube has added sequence numbers as part of their adaptive downloads, and actually require you to send requests to the same URL repeatedly with different parameters in order to get the data. Right now, the code assumes that a single URL is used, and you can simple specify the content-range that you want to download. 

It's going to take me a little while to write proper sequence downloading for this given my schedule this week, so please bear with me for a little while while I work this out.

**Comment by tfdahlin** [comment] 2020-11-05 04:29
I believe that [this branch](https://github.com/tfdahlin/pytube/tree/fix/404-error-on-adaptive) in my fork fixes this issue. I will need to spend some time writing unit tests for it before I make a PR and merge it, but I'd appreciate some feedback on if it works for others or not.

**Comment by GustavoStahl** [comment] 2020-11-05 14:45
@tfdahlin I tested your branch with some videos that were resulting in Error 404 and it worked very well

**Comment by tfdahlin** [comment] 2020-11-05 14:52
Glad to hear it @GustavoStahl. I'll work on getting the unit tests written for my branch, then I'll make a PR, hopefully by end of week.

**Comment by GustavoStahl** [comment] 2020-11-05 20:59
@tfdahlin Actually, now the same videos i tested before are being saved with duration 0 seconds

**Comment by tfdahlin** [comment] 2020-11-05 21:22
@GustavoStahl that's unusual. What videos are you having problems with so I can try and track down the issue?

**Comment by tfdahlin** [comment] 2020-11-05 21:23
Additionally, can you give me the code for how you're downloading them so I can try to replicate the issue?

**Comment by GustavoStahl** [comment] 2020-11-05 22:25
@tfdahlin  Sure, here it goes

**Code**
```
from pytube import YouTube
YouTube('https://www.youtube.com/watch?v=rUWxSEwctFU').streams.filter(adaptive=True).order_by('resolution').last().download() # Works well
YouTube('https://www.youtube.com/watch?v=60hUgAjmHG4').streams.filter(adaptive=True).order_by('resolution').last().download() # Wrong metadata
YouTube('https://www.youtube.com/watch?v=aZeIzUvt3kg').streams.filter(adaptive=True).order_by('resolution').last().download() # Wrong metadata
```
**Metadata for each video**
![combine_images (6)](https://user-images.githubusercontent.com/51406079/98302965-1e618980-1f9c-11eb-9cb0-e03b1b3e5357.png)

**Comment by tfdahlin** [comment] 2020-11-05 22:45
@GustavoStahl Cool, thanks, I'll look into it. I know that the metadata is incorrect, but are you able to play the videos without the duration, for example with VLC player? I'm wondering if it's just an issue where the metadata needs to be corrected, or if the download is failing

**Comment by GustavoStahl** [comment] 2020-11-05 23:29
@tfdahlin I can watch the videos normally, the only problem is the metadata

**Comment by tfdahlin** [comment] 2020-11-05 23:37
Ok, I'll see if I can get that metadata issue fixed

**Comment by tfdahlin** [comment] 2020-11-06 01:18
@GustavoStahl spent a few hours digging around, and it looks like the way that these files are sent, this metadata simply doesn't exist in the file that gets downloaded. Because of the way that YouTube streams these files, it simply doesn't include the duration as part of the metadata that they transmit, so I don't think there's an easy way for me to fix this problem. If you have ffmpeg installed, it looks like you can fix the duration issue by running `ffmpeg -i <input_file_name> -c copy <output_file_name>`, which will create a copy of the file with the duration metadata patched in, but I'm not sure if I'm comfortable trying to patch metadata into the filestream. I'll look into it a little bit more, but I don't want to make promises.

**Comment by GustavoStahl** [comment] 2020-11-06 12:42
@tfdahlin That's odd, because when i first tried your fork everything went well, suddenly ~3 hours later this metadata corruption happens. As for the patch, no worries, i'll try this ffmpeg approach.

**Comment by tfdahlin** [comment] 2020-11-06 15:07
@GustavoStahl it's entirely possible that youtube is making some changes to how it creates the partitioned files, and that they aren't including this metadata any more. While I was looking into this problem, I found a few cases where people were losing the metadata due to the way that the files were getting partitioned and streamed on-the-fly, and in YouTube's case, it might not make sense to even fix that problem

**Comment by tfdahlin** [comment] 2020-11-07 02:24
Working on those unit tests now, hopefully going to have a PR ready late tonight or tomorrow. Still don't think I can fix the metadata issue for now, but I'll make a new issue for it once this PR get's merged.

**Comment by tfdahlin** [comment] 2020-11-07 18:32
made a PR with unit tests for this here: https://github.com/nficano/pytube/pull/799

**Closed as completed** 2020-11-08 16:50 UTC

**Comment by XM-WANG** [comment] 2021-03-31 03:36
May I know if this "404" problem is fixed or not? Why I still have this problem in 2021 XD

**Comment by tfdahlin** [comment] 2021-03-31 19:11
@XM-WANG this problem should be fixed as of November of last year. Check to make sure that you have the most recent version of pytube with the following code:
```python
import pytube
print(pytube.__version__)
```

Currently, pytube is on version 10.6.1. If you're using an older version, you can update with `python -m pip install --upgrade pytube`

**Comment by XM-WANG** [comment] 2021-04-01 01:52
> @XM-WANG this problem should be fixed as of November of last year. Check to make sure that you have the most recent version of pytube with the following code:
> 
> ```python
> import pytube
> print(pytube.__version__)
> ```
> 
> Currently, pytube is on version 10.6.1. If you're using an older version, you can update with `python -m pip install --upgrade pytube`

Thanks for your kindly reply! But I actually use the newest `pytube`. The screenshot is shown below. I print out:
1. `pytube` version.
2. URL. (The video is embarrassing that I masked the URL. XD)
3. The stream info. (I can get the stream. But when going to `download()`, I get the 404 error.)
`pytube` works well for most of the videos but I still meet the 404 error in a few cases. If this is because of the `requests` version?
![image](https://user-images.githubusercontent.com/43406982/113232543-e999fa00-92cf-11eb-8a4b-56485e4ef625.png)

**Comment by tfdahlin** [comment] 2021-04-01 04:05
oh, that's weird! I'll see if I can figure out why that's happening. Can you give me an example of a video where you're having this issue? You said you've had it happen only occasionally, so I'll need to see an example of one that doesn't work so I can try to figure out what's causing the problem

**Comment by XM-WANG** [comment] 2021-04-01 05:29
> oh, that's weird! I'll see if I can figure out why that's happening. Can you give me an example of a video where you're having this issue? You said you've had it happen only occasionally, so I'll need to see an example of one that doesn't work so I can try to figure out what's causing the problem

Sure. Enjoy this music!

>https://youtu.be/-WBmBii_aCs

![image](https://user-images.githubusercontent.com/43406982/113247736-2b399d80-92ee-11eb-8254-36e499bb471b.png)

**Comment by XM-WANG** [comment] 2021-04-01 05:36
My environment:

request == 2.25.1
pytube == 10.6.1
python == 3.6.10
GCC == 4.2.1

Thanks for your kindly help. Please let me know if you need more info to repeat this ERROR.

**Comment by XM-WANG** [comment] 2021-04-01 12:04
> oh, that's weird! I'll see if I can figure out why that's happening. Can you give me an example of a video where you're having this issue? You said you've had it happen only occasionally, so I'll need to see an example of one that doesn't work so I can try to figure out what's causing the problem

Hey, it's hard to say... I did nothing but just retry the bad case. It works for me! Anyway, thanks a lot for your help!

**Comment by ellisju37073** [comment] 2021-06-21 16:43
I have the following code and getting a 404 error. It worked 2 weeks ago

#import library
from tkinter import *
from pytube import YouTube
#creating window
root = Tk()
#setting width and height of window
root.geometry('500x250')
#title for window
root.title("Justin Ellis presents")
#set background color
root["bg"]="blue"
#Label for heading
Label(root,text = 'Justin Ellis Youtube Video Downloader', font ='arial 18 bold',fg="white",bg="#D55B06").pack()
#declaring variable
link = StringVar()
#label for heading
Label(root, text = 'Paste video Link Here:', font = 'arial 15 bold',bg="#D55B06").place(x= 160 , y = 60)
#textbox/entrybox for getting link of video
link_enter = Entry(root, width = 60,textvariable = link).place(x = 72, y = 90)
#function for downloading
def YouTubeDownloader():
    #applying validation
    if link.get()!="":
     #getting url
     url =YouTube(str(link.get()))
     video = url.streams.first()
     #download video
     video.download()
     #show messsage
     Label(root, text = 'Video is downloaded successfully', font = 'arial 15',bg="#D55B06",fg="white").place(x= 70 , y = 210)
     root.destroy()
    else:
        Label(root, text='Link is empty', font='arial 15',bg="#D55B06",fg="white").place(x=180, y=210)
#button for download
Button(root,text = 'Download', font = 'arial 15 bold' ,bg = 'red',fg="white", padx = 1, command = YouTubeDownloader).place(x=180 ,y = 150)
#Run Application
root.mainloop()


Traceback (most recent call last):
  File "C:\Users\12069\AppData\Local\Programs\Python\Python38-32\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:/Users/12069/PycharmProjects/cne330finalproject/youtube_downloader.py", line 31, in YouTubeDownloader
    video = url.streams.first()
  File "C:\Users\12069\PycharmProjects\cne330finalproject\venv\lib\site-packages\pytube\__main__.py", line 310, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\12069\PycharmProjects\cne330finalproject\venv\lib\site-packages\pytube\__main__.py", line 213, in fmt_streams
    if "adaptive_fmts" in self.player_config_args:
  File "C:\Users\12069\PycharmProjects\cne330finalproject\venv\lib\site-packages\pytube\__main__.py", line 187, in player_config_args
    self._player_config_args = self.vid_info
  File "C:\Users\12069\PycharmProjects\cne330finalproject\venv\lib\site-packages\pytube\__main__.py", line 280, in vid_info
    return dict(parse_qsl(self.vid_info_raw))
  File "C:\Users\12069\PycharmProjects\cne330finalproject\venv\lib\site-packages\pytube\__main__.py", line 108, in vid_info_raw
    self._vid_info_raw = request.get(self.vid_info_url)
  File "C:\Users\12069\PycharmProjects\cne330finalproject\venv\lib\site-packages\pytube\request.py", line 52, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
  File "C:\Users\12069\PycharmProjects\cne330finalproject\venv\lib\site-packages\pytube\request.py", line 36, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\12069\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\12069\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\12069\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\12069\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\12069\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\12069\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by tfdahlin** [comment] 2021-06-21 17:19
@ellisju37073 you're probably using a pytube version <10.8.5. There was a new release about 3 days ago that fixed a 404 error. You can update to the latest version with `python -m pip install --upgrade pytube`, and confirm that you're using the latest version with the following code:
```python
import pytube
print(pytube.__version__)  # Should output 10.8.5, as of the time of writing this comment
```

**Comment by ellisju37073** [comment] 2021-06-21 18:05
nevermind it was 10.8.4 not 5 sorry about that

**Comment by VisionsOfDrifting** [comment] 2021-07-03 19:51
> @ellisju37073 you're probably using a pytube version <10.8.5. There was a new release about 3 days ago that fixed a 404 error. You can update to the latest version with `python -m pip install --upgrade pytube`, and confirm that you're using the latest version with the following code:
> 
> ```python
> import pytube
> print(pytube.__version__)  # Should output 10.8.5, as of the time of writing this comment
> ```

Thank you for this, I will keep an eye on the releases.

**Comment by Chillysinger17** [comment] 2021-07-24 09:00
I have pytube version 10.9.3 but still error 404 is coming it was working 2-3 months ago but now its not working😕

**Comment by tfdahlin** [comment] 2021-07-24 15:36
@Chillysinger17 this 404 is a new issue, it's being worked on.

**Comment by RONNCC** [comment] 2021-07-24 21:26
@Chillysinger17  Since this is not an official google library, sometimes Youtube updates can break portions of it
