### ISSUE TITLE
[BUG] Empty streams for some videos

### ISSUE THREAD

**Issue by aklajnert** [pytube/pytube#872] opened 2020-12-13 07:33 UTC
For some links, the `streams` property is empty, and the `get_audio_only()` method returns None. I've identified a few such links that seems to be reproducible. Here's my test code that shows the problem:  

```python
from pytube import YouTube

FAILING = [
    "https://www.youtube.com/watch?v=L6nrMAFCzhg",
    "https://www.youtube.com/watch?v=T8de-31Hu7g",
    "https://www.youtube.com/watch?v=Y08HWyVSMxg",
    "https://www.youtube.com/watch?v=WchEW9LkK94",
]

OK = [
    "https://www.youtube.com/watch?v=7lYMmW2kPpQ",
    "https://www.youtube.com/watch?v=7eVQHt690nk",
    "https://www.youtube.com/watch?v=4bscOLDng0o",
]

for fail in FAILING:
    yt = YouTube(fail)
    stream = yt.streams.get_audio_only()

    # that's unexpected, stream shouldn't be None
    assert stream is None
    assert len(yt.streams) == 0

for ok in OK:
    yt = YouTube(ok)
    stream = yt.streams.get_audio_only()

    # same code, different links - all good
    assert stream is not None
    assert len(yt.streams) > 0
```

I've tested on freshly created virtualenv and the newest `pytube`. Same error on Windows and Ubuntu (WSL).

**Comment by krishnarajt** [comment] 2020-12-13 09:20
> For some links, the `streams` property is empty, and the `get_audio_only()` method returns None. I've identified a few such links that seems to be reproducible. Here's my test code that shows the problem:
> 
> ```python
> from pytube import YouTube
> 
> FAILING = [
>     "https://www.youtube.com/watch?v=L6nrMAFCzhg",
>     "https://www.youtube.com/watch?v=T8de-31Hu7g",
>     "https://www.youtube.com/watch?v=Y08HWyVSMxg",
>     "https://www.youtube.com/watch?v=WchEW9LkK94",
> ]
> 
> OK = [
>     "https://www.youtube.com/watch?v=7lYMmW2kPpQ",
>     "https://www.youtube.com/watch?v=7eVQHt690nk",
>     "https://www.youtube.com/watch?v=4bscOLDng0o",
> ]
> 
> for fail in FAILING:
>     yt = YouTube(fail)
>     stream = yt.streams.get_audio_only()
> 
>     # that's unexpected, stream shouldn't be None
>     assert stream is None
>     assert len(yt.streams) == 0
> 
> for ok in OK:
>     yt = YouTube(ok)
>     stream = yt.streams.get_audio_only()
> 
>     # same code, different links - all good
>     assert stream is not None
>     assert len(yt.streams) > 0
> ```
> 
> I've tested on freshly created virtualenv and the newest `pytube`. Same error on Windows and Ubuntu (WSL).

I am facing the same issue, but I need an urgent fix, as i am using this version for my project, Can you provide examples of a few more links that work? so i can atleast demo it, or what could be a desparate fix?

also, the same is happening with playlists. Here is an example that doesnt work
https://www.youtube.com/watch?v=-GhzpvvIXlM&list=PLS1QulWo1RIY6fmY_iTjEhCMsdtAjgbZM
The output of Playlist.video_urls() also returns a `None` type

**Comment by PC-02** [comment] 2020-12-13 13:07
Been having the same issue for a while now, some links I found that don't work:

https://www.youtube.com/watch?v=u5CVsCnxyXg
https://www.youtube.com/watch?v=GPUg7n8-M6o
https://www.youtube.com/watch?v=9YgmMJJ34k4
https://www.youtube.com/watch?v=vnLAa6_hB9A
https://www.youtube.com/watch?v=Mw5mAozjC6M
https://www.youtube.com/watch?v=-hptmburu3U
https://www.youtube.com/watch?v=lflsO7pxSE0
https://www.youtube.com/watch?v=mvJjmWTg7Qo
https://www.youtube.com/watch?v=DCi9I7ylt14

All of the above can be reproduced, might be helpful with looking for a pattern.

**Comment by tfdahlin** [comment] 2020-12-13 15:54
hi @aklajnert, just to confirm, when you run 
```python
import pytube
print(pytube.__version__)
```
does it show `10.1.0`? Those videos are working just fine for me:
![image](https://user-images.githubusercontent.com/9667869/102016924-86408800-3d31-11eb-9926-05b5a032a79c.png)

**Comment by aklajnert** [comment] 2020-12-13 16:06
@tfdahlin It's `10.0.0` actually, but that's  the one that gets installed as the newest one:
```
> pip install --upgrade pytube
Requirement already up-to-date: pytube in /venv/pytube/lib/python3.8/site-packages (10.0.0)
```

**Comment by tfdahlin** [comment] 2020-12-13 16:12
Yeah, that's where the problem is. I'm working on getting something set up so that the pypi repository gets updated more quickly. I can make changes to the repo itself, but don't have access to pypi, so sometimes it takes a while for my bugfixes to get pushed to pypi. 

The command you should be using to install pytube from source is `python -m pip install git+https://github.com/nficano/pytube`. This should have been in the instructions when you made this ticket, but maybe I can make that more clear.

**Comment by tfdahlin** [comment] 2020-12-13 16:20
We're hoping that we'll have the process for updating pypi set up sometime this week. The PR is [already written](https://github.com/nficano/pytube/pull/871), Ronnie just needs to review it when he has the time and set a couple of things up.

**Comment by tfdahlin** [comment] 2020-12-13 16:24
@KrishnarajT and @PC-02 I believe your problems are also fixed in the github repository, just not the pypi repository. You should also run python -m pip install git+https://github.com/nficano/pytube to install from source, and see if that fixes the problem for you.

**Comment by krishnarajt** [comment] 2020-12-13 17:30
@tfdahlin yes, the links work perfectly fine now, I had noticed the latest version in the docs, but didnt think of installing from source. Thanks a ton!

**Comment by PC-02** [comment] 2020-12-13 17:33
@tfdahlin The links work now, looks like it was an issue caused by using 10.0.0. Thank you so much!

**Comment by aklajnert** [comment] 2020-12-13 17:42
Thanks @tfdahlin - that makes sense. Anyway, the projects that use `pytube` as dependency cannot just set its version to master, and need to wait for it to be released. But good to know that it is already fixed.

**Closed as completed** 2020-12-13 17:58 UTC
Labels: bug

**Comment by aklajnert** [comment] 2020-12-18 19:10
@tfdahlin - any ETA when the new version will be released to PyPI?

**Comment by tfdahlin** [comment] 2020-12-18 23:02
Hopefully this weekend, depends on when @RONNCC has the chance to either review my PR or push an update manually. He said he'd look into it today, but obviously depends on if he has the time to

**Comment by aklajnert** [comment] 2020-12-28 15:50
@tfdahlin - anything I can do to help with the release? It's a bit unpleasant situation as the package cannot be used as a dependency when not released on PyPi.

**Comment by tfdahlin** [comment] 2020-12-28 17:47
@aklajnert unfortunately, not really at the moment. @RONNCC is the one who has to update the pypi package, and I think he's on vacation and not looking at github currently. I was supposed to be given access to pypi by the owner, but that also hasn't happened yet. I think this is just going to be stuck for a little while longer at this point, likely until after January 1st

**Comment by RONNCC** [comment] 2020-12-28 19:48
@tfdahlin  @aklajnert  sorry my bad here -- done.

**Comment by RONNCC** [comment] 2020-12-28 19:52
> It's a bit unpleasant situation as the package cannot be used as a dependency when not released on PyPi.

This shouldn't be the case -- can you explain a bit more around your problem?

**Comment by tfdahlin** [comment] 2020-12-28 20:52
@RONNCC it has to do with libraries that have pytube as dependencies. There isn't really a good way to tell setuptools to install a package from github if it already exists in pypi as far as I can tell.

**Comment by RONNCC** [comment] 2020-12-29 05:58
@tfdahlin  https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repo-as-a-dependency ?

**Comment by tfdahlin** [comment] 2020-12-29 06:09
I kept trying to get that to work, but it only wanted to install from pip, and I can't work out why

**Comment by tfdahlin** [comment] 2020-12-29 06:11
I'll admit I gave up pretty early because I wasn't sure if I was diving down a rabbit hole unnecessarily

**Comment by aklajnert** [comment] 2020-12-29 10:05
> @tfdahlin https://stackoverflow.com/questions/32688688/how-to-write-setup-py-to-include-a-git-repo-as-a-dependency ?

I've found that also, but it seems that you can't release your package on PyPI with dependencies as links according to [this](https://github.com/pypa/pip/issues/4187#issuecomment-415667805)

**Comment by RONNCC** [comment] 2020-12-29 19:54
@aklajnert  makes sense - seems PyPI essentially restricted it since you're essentially running code _from anywhere_
