### ISSUE TITLE
Network problems cause Downloads to freeze

### ISSUE THREAD

**Issue by bigbluedeer** [pytube/pytube#947] opened 2021-02-28 14:11 UTC
When downloading any video (or audio for that matter), when my computer experiences network problems such as sudden disconnects or reconnects to other networks, the download just freezes. The file does no longer update, its size does not grow and the script seems to have stopped making any requests to the network (looked it up with a network monitor). Over a span of 1h after my pc got disconnected from the network (reconnected 5 minutes later), the video file did not grow/update, making it seem like the download is just frozen. 
I use multiprocessing process to handle downloads. When killing the script, the following error message appears

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/me/ytscript.py", line 1986, in download
    vid.download(output_path=sys.path[0], filename=in_vid)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/streams.py", line 260, in download
    for chunk in request.stream(self.url):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytube/request.py", line 112, in stream
    chunk = response.read(chunk_size)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 447, in read
    n = self.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 491, in readinto
    n = self.fp.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1049, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 908, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

it seems like a timeout somewhere would be a good idea

**Comment by tfdahlin** [comment] 2021-02-28 16:42
hi @bigbluedeer -- we can defintely add a timeout to this, my concern would be setting the timeout appropriately. Part of the objective with pytube is to allow extremely slow internet connections to download videos, so we'd need to find a way to balance that appropriately. I'll look into a potential solution for this

**Comment by bigbluedeer** [comment] 2021-02-28 17:30
maybe just make it a parameter for the download function? someone with faster internet can set it to like 5 minutes, while someone with slower connection does not need to set it at all.
or the other way around, if you are getting timeouts too often, just turn the timeouts off

**Comment by bigbluedeer** [comment] 2021-02-28 17:31
or the other way around, if you are getting timeouts too often, just turn the timeouts off

**Comment by thewh1teagle** [comment] 2021-03-02 11:04
I'm facing the same issue. 
I think that timeout would be great as a feature currently, and also it can be temporarily solution for that freezing.

**Comment by tfdahlin** [comment] 2021-03-09 01:18
Once my other PRs are merged, I'll look into implementing a clean way of setting a timeout, and potentially a retry policy for this.

**Comment by tfdahlin** [comment] 2021-04-03 21:53
Sorry this has taken so long, I'm working on a solution for this right now.

**Comment by tfdahlin** [comment] 2021-04-03 22:45
see #966 for the what I currently have

**Closed as completed** 2021-04-04 19:31 UTC

**Comment by jihuun** [comment] 2021-06-20 03:08
Is this a problem made by the network connection instability? 
I have the same issue on pytube10.8.5. but not sure if my network connection is stable or not. Thanks!

**Comment by tfdahlin** [comment] 2021-06-20 14:28
hi @jihuun -- yes, this problem is usually caused by network instability. If you have a potentially unstable connection, there are a few things you can do to try and fix the issue.

The first is to use the additional arguments for the `Stream.download()` method, like this:
```python
yt = YouTube(url)
stream = yt.streams.first()
stream.download(timeout=15,retries=5)
```

You might also try setting the `default_range_size to a smaller value, which sets the portion of a video downloaded at a time. It defaults to 9MB, but it may be appropriate to use a smaller value on slower or unreliable connections. You would change that like this:
```python
import pytube.request
pytube.request.default_range_size = 9437184  # this is 9MB, change the value to something smaller
```
