### ISSUE TITLE
Playlist class only grab 100 id from the playlist

### ISSUE THREAD

**Issue by leaf918** [pytube/pytube#292] opened 2018-06-29 09:19 UTC
can you fix this,please.

**Comment by fja05680** [comment] 2018-06-29 18:02
This is a duplicate of #251 and should be closed.

**Comment by vn-ki** [comment] 2018-06-29 18:04
Duplicate of #251. If you really want it, you can try pafy which is another python library which does this(try `pafy.get_playlist2`). `pafy` uses youtube data api to acheive this. Also note that pafy is a lot slower to startup because it uses youtube-dl as a backend.

**Closed as completed by vn-ki** 2018-06-29 18:04 UTC
