### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'span'

### ISSUE THREAD

**Issue by bubersome** [pytube/pytube#1171] opened 2021-11-23 03:53 UTC
(venv) ➜  pytube pytube https://www.youtube.com/watch\?v\=5Q2Pc-e-8Qc
Loading video...
Traceback (most recent call last):
  File "/Users/32uni/PycharmProjects/pytube/venv/bin/pytube", line 8, in <module>
    sys.exit(main())
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 53, in main
    _perform_args_on_youtube(youtube, args)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 60, in _perform_args_on_youtube
    download_highest_resolution_progressive(
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cli.py", line 474, in download_highest_resolution_progressive
    stream = youtube.streams.get_highest_resolution()
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cipher.py", line 44, in __init__
    self.throttling_array = get_throttling_function_array(js)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/cipher.py", line 323, in get_throttling_function_array
    str_array = throttling_array_split(array_raw)
  File "/Users/32uni/PycharmProjects/pytube/venv/lib/python3.8/site-packages/pytube/parser.py", line 158, in throttling_array_split
    match_start, match_end = match.span()
AttributeError: 'NoneType' object has no attribute 'span'
(venv) ➜  pytube

**Comment by 89z** [comment] 2021-11-23 03:57
Why do you have the `pytube` command twice?

**Comment by mitchellspryn** [comment] 2021-11-23 04:34
Seems like [this is a potential fix](https://stackoverflow.com/questions/70060263/pytube-attributeerror-nonetype-object-has-no-attribute-span)

**Comment by glubsy** [comment] 2021-11-23 14:04
Duplicate of #1163 please use the search feature before posting.

**Comment by Xcvii-Bix** [comment] 2021-11-23 17:36
Go to the this directory on your pc>>>>> C:\Users\....................\anaconda3\Lib\site-packages 
Delete the following folders
1. Requests
2. pytube(all versions)
3. urllib( all versions)
4. youtube
5. youtube downloader
6. any folders with (1, 2,3 ,4,5 above on their names)
7.
pip install them one by one after uninstalling

**Closed as completed** 2021-12-10 22:06 UTC
