### ISSUE TITLE
[BUG]Pytube cannot access streams of some youtube videos

### ISSUE THREAD

**Issue by Rohanator2314** [pytube/pytube#1054] opened 2021-07-15 09:19 UTC
**The bug**
Pytube cannot access streams of some youtube videos

**To Reproduce**
A quick test shows this. I ran this in cmd:
```
yt = YouTube('https://www.youtube.com/watch?v=nb6ou_k4OzM')
print(yt.streams)
```

**Expected behavior**
When running this code in the past (on the same video), a list of streams was shown

**Output**
The error is as follows:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 311, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 223, in fmt_streams
    extract.apply_signature(self.player_config_args, fmt, self.js)
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 476, in apply_signature
    new_n = cipher.calculate_n(initial_n)
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\cipher.py", line 63, in calculate_n
    raise TypeError(f'{curr_func} is not callable.')
TypeError: 302823254 is not callable.
```

**System information**
Please provide the following information:
- Python version: 3.9
- Pytube version: 10.9.2
- Command used to install pytube : `pip install pytube` (and pytube3), then `pip install git+https://github.com/pytube/pytube`

**Comment by Rohanator2314** [comment] 2021-07-15 09:39
After some more testing, it seems that this is some sort of change on YouTubes end for videos in playlists. The same code that could download a playlist before will no longer work. Hopefully their is still a way to fix this

**Comment by tfdahlin** [comment] 2021-07-16 00:37
Looking into a fix for this

**Comment by tfdahlin** [comment] 2021-07-16 00:46
Well that's weird. I was able to reproduce this bug like 20 minutes ago, and now I can't any more.

**Comment by Rohanator2314** [comment] 2021-07-16 01:06
A good sign???

**Comment by Rohanator2314** [comment] 2021-07-16 01:10
It works for me aswell

**Comment by tfdahlin** [comment] 2021-07-16 01:11
Could indicate one of several things:
1. YouTube made a change and reverted it (less likely, but might explain it)
2. I'm getting different results in my web requests than other people (possibly b/c of geofencing. This makes it *extremely* difficult for me to try and debug)
3. Perhaps I need to get rid of the `base.js` caching, and people are experiencing this transiently because of a change to the player js while downloading multiple videos. I was afraid this *may* happen at some point, but wasn't sure.

If we get another issue like this in the future, I'll strip the caching code, which will cause a slight performance hit, but should permanently solve the issue if it is indeed the 3rd case.

**Closed as completed** 2021-07-16 23:11 UTC
Labels: bug, duplicate

**Comment by tfdahlin** [comment] 2021-07-17 20:43
I'm adding some code that will try and fetch a newer version of the player js if it encounters this error, will try to get it merged today or tomorrow after some additional testing

**Comment by tfdahlin** [comment] 2021-07-21 00:49
The code that's supposed to detect these failures and try to refresh the js cache has been pushed as part of v10.9.3

**Comment by BOKUS123** [comment] 2022-11-15 23:01
Hello, I had the same problem as described here. I dont know if it helps you here with that issue. But it helped me to use Pytube again successfully. 

After I updated all outdated packes (Thats how I found them: pip list --outdated) I was able to use it again. 

I updated them in power shell with that statement: "pip freeze | %{$_.split('==')[0]} | %{pip install --upgrade $_}" (https://www.activestate.com/resources/quick-reads/how-to-update-all-python-packages/ or https://www.youtube.com/watch?v=cJduUNbU9ao) 

Greetings
