### ISSUE TITLE
Redirects from pyvideo style links

### ISSUE THREAD

**Issue by elzilrac** [pytube/pytube#27] opened 2016-06-02 19:09 UTC
There's a different naming schema; it would be great if there was a redirect from the old pyvideo-style links to the new pytube style links:
https://github.com/Nitron/pelican-alias

**Comment by logston** [comment] 2016-07-17 03:42
I think this is a duplicate of https://github.com/pytube/pytube/issues/64 Please reopen if it is not.

**Closed by logston** 2016-07-17 03:42 UTC
Labels: enhancement
