### ISSUE TITLE
Unable to make YouTube object

### ISSUE THREAD

**Issue by ghost** [pytube/pytube#843] opened 2020-11-24 07:31 UTC
```
Traceback (most recent call last):
  File "/home/samip/Python_programming/Cmd based/YTdownloader.py", line 3, in <module>
    video = YouTube('https://youtu.be/9bZkp7q19f0')
  File "/home/samip/Sublime_Envs/venv(pygame)/lib/python3.6/site-packages/pytube/__main__.py", line 91, in __init__
    self.prefetch()
  File "/home/samip/Sublime_Envs/venv(pygame)/lib/python3.6/site-packages/pytube/__main__.py", line 183, in prefetch
    self.js_url = extract.js_url(self.watch_html)
  File "/home/samip/Sublime_Envs/venv(pygame)/lib/python3.6/site-packages/pytube/extract.py", line 143, in js_url
    base_js = get_ytplayer_config(html)["assets"]["js"]
KeyError: 'assets'
```

**Comment by RahulARanger** [comment] 2020-11-24 09:49
Duplicate of #834 and it was resolved.

**Comment by tfdahlin** [comment] 2020-11-24 15:52
hi @Samip-Karki this problem is caused by having an outdated version of pytube. To install the latest version, please run the following:
`python -m pip uninstall pytube pytube3 pytubex`
`python -m pip install pytube`

**Closed as completed by tfdahlin** 2020-11-24 15:52 UTC
Labels: duplicate
