### ISSUE TITLE
Travis-CI fails on PR from forked repo

### ISSUE THREAD

**Issue by tfors** [pytube/pytube#60] opened 2016-06-03 18:31 UTC
Forking the repo and then submitting a PR causes Travis-CI to fail with the following erro.:

> The command "openssl aes-256-cbc -K $encrypted_57e34ca198d1_key -iv $encrypted_57e34ca198d1_iv -in .ssh/travis.enc -out .ssh/travis -d" failed and exited with 1 during .

**Comment by logston** [comment] 2016-07-17 03:00
No way around this unless I get rid of the preview site or make the deploy key public. The issue is that forks do not have access to env vars in travis ci for security reasons. I really like the preview site and don't want to make the deploy key public right now. @tfors Any suggestions? Maybe we could put the key decryption in the travis.sh file after the main tests? Instead of before the test suite begins? Builds would still fail but at least tests would run? Unfortunately, there are no ENV VARs we can use to identify if the build is for a PR from this repo vs. a fork so we could not conditionally decrypt these env vars.

**Comment by logston** [comment] 2016-07-21 00:05
It stinks that we can not resolve this issue easily or clearly. However, since there is not much we can do for this issue, I think its best we close this issue so that efforts can stay focused on pytube/data. Also, I don't see this issue as a major road block. Each time someone submits a PR, I usually end up adding them as a collaborator on the repo anyway. Please reopen if you feel differently @tfors.

**Closed by logston** 2016-07-21 00:05 UTC
Labels: bug
