### ISSUE TITLE
[BUG] HTTP Error 429: Too Many Requests from linux server

### ISSUE THREAD

**Issue by zabir-nabil** [pytube/pytube#1306] opened 2022-04-30 14:35 UTC
**Describe the bug**
HTTP Error 429: Too Many Requests

```
ytb = YouTube(vid)
ytb.streams.filter(res="360p").first().download(output_path = f"{seg_id}_{ch}", filename = f"vid_{vid_idx}.mp4")
            
```
**To Reproduce**
I'm on an ubuntu 18. The script was running fine yesterday, but now I am getting this error repeatedly.

**Expected behavior**

**Output**
If pytube raises an exception, please provide the full traceback for the exception.
HTTP Error 429: Too Many Requests

**System information**
Please provide the following information:
- Python version (run `python --version`)
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
- Pytube version (run `print(pytube.__version__)` in python)
- 12.0.0

**Comment by glubsy** [comment] 2022-04-30 19:55
Can you explain why you think this is related to pytube?

**Comment by wkrettek** [comment] 2022-05-03 03:51
Usually this is caused by your IP being rejected by Youtube for some reason or other. If you have a VPN, try changing your IP and seeing if it works

**Comment by Justxd22** [comment] 2022-06-25 16:49
@zabir-nabil this isn't pytube fault, YouTube blocked your ip for too many requests, restart your server and it should be fine, please close this

**Closed as completed** 2022-09-29 11:32 UTC
Labels: bug
