### ISSUE TITLE
Return Playlist Array Empty

### ISSUE THREAD

**Issue by Master-JS** [pytube/pytube#854] opened 2020-12-04 08:44 UTC
```
list = Playlist("My Link")
print(list.title)
print(list.video_urls)
for video in list.videos:
     print(video)
     print("Hello!!")


print("end")
```

-----
Return:
```
Playlist Title
1  
[] 
end
```

-----
What's the Problem?

**Comment by maneletorres** [comment] 2020-12-04 20:07
It happens the same to me. I have gone crazy thinking that I had broken something in my application until I saw this post. Thank you @Master-JS for reporting.
Let's wait for a solution.

**Comment by tfdahlin** [comment] 2020-12-05 01:51
This is a duplicate of #848 , so i'm going to close this. I'm going to try and find a fix for this this weekend.

**Closed as completed** 2020-12-05 01:52 UTC
Labels: bug, duplicate
