### ISSUE TITLE
Can't get a value of streams.

### ISSUE THREAD

**Issue by wimpykid719** [pytube/pytube#877] opened 2020-12-16 03:15 UTC
I tried that code but It won't back the value. It will take a empty list.
What shoud I do??
Some of url is works fine. So depends on url why??
`https://www.youtube.com/watch?v=cw4-bqSpVdo` working
`https://www.youtube.com/watch?v=tG7wLK4aAOE` not working

**version**
pytube==10.0.0

**code**
```
from pytube import YouTube
print(YouTube('https://www.youtube.com/watch?v=1zZkwMNp0gw').streams)

```

**results**
`[]`

**Comment by tfdahlin** [comment] 2020-12-17 04:39
hi @wimpykid719 this problem is fixed in pytube 10.1.0, please install the latest version from github with `python -m pip install git+https://github.com/nficano/pytube`

**Comment by ghw2020** [comment] 2020-12-17 06:22
Hello Taylor, I did some simple tests, seems to work again. Thanks for the quick bugfix.

**Comment by wimpykid719** [comment] 2020-12-17 06:34
Thank you so much I will try to update.

**Comment by mytja** [comment] 2020-12-17 12:09
Hello!
I think it still doesn't work

Videos:
https://www.youtube.com/watch?v=Kx7B-XvmFtE
and many many others...

I'm using latest version from GitHub

```
yt = YouTube('https://youtube.com/watch?v='+trackId)
yt_streams = yt.streams.first().download()
AttributeError: 'NoneType' object has no attribute 'download'
```

**Comment by tfdahlin** [comment] 2020-12-17 14:25
@mytja that example that you gave works fine for me. Can you make sure that if you run the following:
```python
import pytube
print(pytube.__version__)
```
that it prints out 10.1.0?

**Comment by mytja** [comment] 2020-12-17 15:42
Yes.
 I used also ```python3 -m pip install git+https://github.com/nficano/pytube```

**Comment by tfdahlin** [comment] 2020-12-17 16:51
Can you give me some more examples of videos that don't work for you then? I can't reproduce the problem with the video you provided, so more samples might help

**Comment by mytja** [comment] 2020-12-17 17:47
I will give you them tomorrow. It is quite late now...

**Comment by mytja** [comment] 2020-12-18 07:15
https://youtube.com/watch?v=rNQiqZKndG4
https://youtube.com/watch?v=8skNEnFoeEk
https://youtube.com/watch?v=e8WoWk4b3D0
https://youtube.com/watch?v=Urmvg54hldk
https://youtube.com/watch?v=KKHKQ5Gyfzo
https://youtube.com/watch?v=7O4FqXvBgeo

Those are a few that don't download! They are all well known songs, but when I download not so known songs or not copyrighted songs, it is okay!

**Comment by mahmoud-abdallah863** [comment] 2020-12-19 00:05
Hello @mytja,
I had the same problem but when I changed to the GitHub version, it was resolved.
I have tried the videos you mentioned, they works for me.

**Comment by wimpykid719** [comment] 2020-12-19 07:42
I update to  pytube-10.1.0 then  it worked.

**Closed as completed** 2020-12-19 07:42 UTC
Labels: bug

**Comment by mytja** [comment] 2020-12-19 08:47
Yeah, I'm on GitHub version.
I used pip install git+https://github.com/nficano/pytube

**Comment by mytja** [comment] 2020-12-19 09:40
I looked at my requirements file, and i defined to install from PyPI after installing it from GitHub... 😅
Sorry for bothering you!

**Comment by 8galigator8** [comment] 2022-06-06 22:06
> Yeah, I'm on GitHub version. I used pip install git+https://github.com/nficano/pytube



I have a problem with this command, the error message is :

ERROR: Error [WinError 2] Le fichier spécifié est introuvable while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
