### ISSUE TITLE
[BUG] Installation link in documentation points to Playlists page not actual installation instructions.

### ISSUE THREAD

**Issue by dragon788** [pytube/pytube#883] opened 2020-12-19 22:00 UTC
Title says it all, the installation link in the documentation points to the Playlists page not the actual installation instructions.

I'm not familiar with how the rst gets converted to the ReadTheDocs but it appears to be goofed.

File that creates bad link
https://github.com/nficano/pytube/blob/master/docs/index.rst

Bad URL

https://python-pytube.readthedocs.io/en/latest/user/playlist.html#install

Correct URL

https://python-pytube.readthedocs.io/en/latest/user/install.html

**Comment by tfdahlin** [comment] 2020-12-20 14:49
Good catch! That's... actually super weird, and I don't think it should be doing that. I think I may have found the cause though, so I'll see if I can fix that.

**Comment by tfdahlin** [comment] 2020-12-20 15:01
Figured out the issue, I had mislabeled the playlist doc when I created it. The link should be fixed now!

**Closed as completed by tfdahlin** 2020-12-20 15:01 UTC
Labels: bug
