### ISSUE TITLE
[BUG] Specific video isn't Downloading

### ISSUE THREAD

**Issue by Sasiam** [pytube/pytube#1012] opened 2021-06-08 18:23 UTC
**Describe the bug**
Doesn't download this video. 

**To Reproduce**
- The video url: ["https://www.youtube.com/watch?v=dyLAGL0DeRs"](https://www.youtube.com/watch?v=dyLAGL0DeRs)

- The code:
`videolink = "https://www.youtube.com/watch?v=dyLAGL0DeRs"
pytube.YouTube(videolink).streams.filter(progressive=True,file_extension='mp4').get_highest_resolution().download()`

**Expected behavior**

Downloads this video.

**Traceback**
```
Traceback (most recent call last):
  File "C:\Code\downloader\test.py", line 8, in <module>
    YouTube("https://www.youtube.com/watch?v=dyLAGL0DeRs").streams.filter(progressive=True,file_extension='mp4').get_highest_resolution().download()
  File "C:\Code\downloader\lib\site-packages\pytube\streams.py", line 258, in download
    for chunk in request.stream(
  File "C:\Code\downloader\lib\site-packages\pytube\request.py", line 181, in stream
    chunk = response.read()
  File "C:\Python\Python392\lib\http\client.py", line 471, in read
    s = self._safe_read(self.length)
  File "C:\Python\Python392\lib\http\client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(3841359 bytes read, 5595825 more expected)
```

**System information**
- Python version Python 3.9.2
- Pytube version 10.8.4

**Comment by tfdahlin** [comment] 2021-06-09 22:42
Hi @Sasiam I'm unable to reproduce this problem. It's possible that it's caused by internet connection issues, which are more likely to occur with particularly large files like this. Did you try this download multiple times, and experience the same problem?

**Comment by Sasiam** [comment] 2021-06-09 23:49
Yes, I've tried downloading it multiple times yesterday. Weirdly enough it worked now. Probably a problem at my end cause now I'm stuck at this video: https://www.youtube.com/watch?v=Q5hNbAaR6tE.

**Comment by Sasiam** [comment] 2021-06-09 23:58
Oh yeah, I forgot it's the same exception message as last time.

```
Traceback (most recent call last):
  File "C:\Code\downloader\test.py", line 8, in <module>
    pytube.YouTube("https://www.youtube.com/watch?v=Q5hNbAaR6tE").streams.filter(progressive=True,file_extension='mp4').get_highest_resolution().download()
  File "C:\Code\downloader\lib\site-packages\pytube\streams.py", line 258, in download
    for chunk in request.stream(
  File "C:\Code\downloader\lib\site-packages\pytube\request.py", line 181, in stream
    chunk = response.read()
  File "C:\Python\Python392\lib\http\client.py", line 471, in read
    s = self._safe_read(self.length)
  File "C:\Python\Python392\lib\http\client.py", line 614, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(76612 bytes read, 9360572 more expected)
```

**Comment by tfdahlin** [comment] 2021-06-11 22:10
Yeah, I'm fairly certain this is caused by intermittent connectivity issues. If you have a slower connection, you might try [changing the default_chunk_size](https://github.com/pytube/pytube/issues/1017#issuecomment-859199946) to see if that helps with the issue. I'm going to close this issue for now since I don't think it's something that we can fix in pytube at the moment.

**Closed as completed by tfdahlin** 2021-06-11 22:10 UTC
Labels: bug
