### ISSUE TITLE
2160p (4K) not showing up

### ISSUE THREAD

**Issue by tylwright** [pytube/pytube#107] opened 2016-08-16 02:18 UTC
Hello,

I love pytube but 1080p and 2160p (4K) should be available options.

For example, this video (https://www.youtube.com/watch?v=IM_HUhmTDoA) is available in 4K but pytube shows the following:

> pytube -r 2160p https://www.youtube.com/watch\?v\=IM_HUhmTDoA
> Make sure you give either of the below specified format/resolution combination.
> ['3gp 144p', '3gp 240p', 'mp4 360p', 'mp4 720p']

Thanks!

**Comment by josegonzalez** [comment] 2016-08-16 07:23
Duplicate of #106.

**Closed as completed by josegonzalez** 2016-08-16 07:23 UTC

**Comment by tylwright** [comment] 2016-08-16 12:53
Is this a duplicate?  The other issue seems to be talking about 1080p only.
