### ISSUE TITLE
Pytube and logging incompatibility

### ISSUE THREAD

**Issue by Moondra** [pytube/pytube#166] opened 2017-10-22 22:25 UTC
I'm using Python 3.6 and Windows 7.

When I import pytube log files aren't generated, but using the same script, if I comment out the pytube import, the log files will be generated:

```
import pytube  #comment out
import cv2
import os
import logging

logging.basicConfig(
                    level=logging.DEBUG,
                    filename ='this_is_a_test_with_pytube.log',
                    format="%(asctime)s:%(levelname)s:%(message)s")


logging.info('Start reading database')
logging.debug('Testing')`
```

**Comment by nficano** [comment] 2017-10-23 17:31
duplicate of https://github.com/nficano/pytube/issues/163

**Closed as completed by nficano** 2017-10-23 17:31 UTC
Labels: duplicate
