### ISSUE TITLE
Unable to download large playlists

### ISSUE THREAD

**Issue by kirpichik** [pytube/pytube#265] opened 2018-04-22 11:25 UTC
When I try to download the entire playlist using:
```
Playlist.download_all()
```
It is possible to download only 100 videos.

**Comment by fja05680** [comment] 2018-05-09 13:47
That limitation is due to the fact that youtube playlist link only shows the first 100 videos in html source.  Showing more of the list requires a use to manually scroll or click 'next'.  There is possibly a programmatic workaround.  For now, you should break up your playlist into sets of 100.

**Comment by fja05680** [comment] 2018-06-29 17:59
This is a duplicate of #251 and should be closed.

**Closed as completed** 2018-06-29 18:01 UTC
